services:

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped  
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DIALECT: ${DB_DIALECT}

    networks:
      - app-network
  
  db: # The database service
    image: postgres # Using the oficial dockerhub image
    container_name: postgres
    networks:
      - app-network # Connect to the network to be used by other containers (ej: the web server)
    environment: # all the enviroment variables defined in the container (see postgres official image docs https://hub.docker.com/_/postgres)
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    volumes:
      # To persist the data in the database we have a volume that persist after container deletion
      # and copy the files from the container to the volume.
      - db-volume:/var/lib/postgresql/data 




networks: # All the networks that connects our containers
  app-network:
    driver: bridge

volumes: # All the named volumes needed to persist data after container deletion
  db-volume: